// src/components/reports/ReportsTable.tsx

import { FileText, Download, CheckCircle2, Loader2 } from "lucide-react";

const mockReports = [
  { id: "REP-9923", project: "PRJ-092: GBI-SCIOS Alpha", author: "System Auto-Scan", date: "2026-06-16 04:30 AM", status: "Generated" },
  { id: "REP-9922", project: "PRJ-093: Riyadh Metro", author: "Admin User", date: "2026-06-15 11:15 AM", status: "Generated" },
  { id: "REP-9921", project: "PRJ-088: NEOM Phase 1", author: "Compliance Engine", date: "2026-06-15 09:00 AM", status: "Processing" },
  { id: "REP-9920", project: "PRJ-094: Jeddah Port", author: "Admin User", date: "2026-06-14 02:45 PM", status: "Generated" },
];

export default function ReportsTable() {
  return (
    <div className="bg-slate-900/50 border border-slate-800 rounded-xl overflow-hidden shadow-xl">
      <div className="p-5 border-b border-slate-800 flex justify-between items-center">
        <h3 className="text-sm font-semibold text-slate-200 uppercase tracking-wider">Sovereign Intelligence Reports</h3>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm whitespace-nowrap">
          <thead className="bg-slate-950/80 text-slate-400 border-b border-slate-800">
            <tr>
              <th className="px-6 py-4 font-medium uppercase tracking-wider text-xs">Report ID</th>
              <th className="px-6 py-4 font-medium uppercase tracking-wider text-xs">Project Target</th>
              <th className="px-6 py-4 font-medium uppercase tracking-wider text-xs">Generated By</th>
              <th className="px-6 py-4 font-medium uppercase tracking-wider text-xs">Timestamp</th>
              <th className="px-6 py-4 font-medium uppercase tracking-wider text-xs">Status</th>
              <th className="px-6 py-4 font-medium text-right uppercase tracking-wider text-xs">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/50">
            {mockReports.map((report) => (
              <tr key={report.id} className="hover:bg-slate-800/30 transition-colors">
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <FileText className="w-4 h-4 text-slate-500" />
                    <span className="font-mono text-xs font-medium text-blue-400">{report.id}</span>
                  </div>
                </td>
                <td className="px-6 py-4 font-medium text-slate-200">{report.project}</td>
                <td className="px-6 py-4 text-slate-400 text-xs">{report.author}</td>
                <td className="px-6 py-4 text-slate-400 font-mono text-xs">{report.date}</td>
                <td className="px-6 py-4">
                  {report.status === "Generated" ? (
                    <div className="flex items-center gap-1.5 text-emerald-400 text-xs font-medium">
                      <CheckCircle2 className="w-3.5 h-3.5" /> Generated
                    </div>
                  ) : (
                    <div className="flex items-center gap-1.5 text-blue-400 text-xs font-medium">
                      <Loader2 className="w-3.5 h-3.5 animate-spin" /> Processing
                    </div>
                  )}
                </td>
                <td className="px-6 py-4 text-right">
                  <button 
                    disabled={report.status !== "Generated"}
                    className="inline-flex items-center gap-2 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed text-slate-200 text-xs font-medium py-1.5 px-3 rounded-md transition-colors border border-slate-700"
                  >
                    <Download className="w-3.5 h-3.5" />
                    PDF
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}